/**
 * Loads ALBUMS and SONGS_DB from the /data JSON files instead of
 * a giant inline JS literal. Songs are loaded lazily per-album via
 * an index built from each album's `tracks` list, plus a manifest
 * of every song id (data/songs/_index.json, generated by
 * scripts/build-song-index.js) so search can work without fetching
 * all 58 files up front.
 */

let albumsCache = null;
let songIndexCache = null; // [{ id, title, titlePinyin, meta }]
const songCache = new Map(); // id -> full song object

export async function loadAlbums() {
  if (albumsCache) return albumsCache;
  const res = await fetch('data/albums.json');
  albumsCache = await res.json();
  return albumsCache;
}

let projectsCache = null;
export async function loadProjects() {
  if (projectsCache) return projectsCache;
  const res = await fetch('data/projects.json');
  projectsCache = await res.json();
  return projectsCache;
}

export async function loadSongIndex() {
  if (songIndexCache) return songIndexCache;
  const res = await fetch('data/songs/_index.json');
  songIndexCache = await res.json();
  return songIndexCache;
}

export async function loadSong(id) {
  if (songCache.has(id)) return songCache.get(id);
  const res = await fetch(`data/songs/${id}.json`);
  if (!res.ok) return null;
  const song = await res.json();
  songCache.set(id, song);
  return song;
}

export async function loadHskDb() {
  const res = await fetch('data/hsk.json');
  return res.json();
}
